### PR TITLE
Fix README.md travis and coveralls badge URL to codingsince1985/geo-golang

### PR DESCRIPTION
**Pull request by dougnukem**
- Fix up readme badges to point to the main repo

### CODE REVIEW

**Comment by dougnukem** [comment]
@codingsince1985 For this to work as repo owner/maintainer you'll need to setup the repo on travis and coveralls. As well us update the `.travis.yml` with encrypted API keys for GEO API and Coveralls.

If you're willing you can give me contributor access to set this up for you.

# Instructions

- https://travis-ci.org - signup and enable repo
- https://coveralls.io - signup and enable repo


## Setting `.travis.yml` encrypted API keys

```
travis encrypt COVERALLS_TOKEN="XYZ" --add

travis encrypt GOOGLE_API_KEY="XYZ" --add --append

travis encrypt BING_API_KEY="YZX" --add --append

travis encrypt HERE_APP_ID="YZX" --add --append
travis encrypt HERE_APP_CODE="YZX" --add --append

travis encrypt MAPBOX_API_KEY="YZX" --add --append

travis encrypt MAPQUEST_NOMINATUM_KEY="YZX" --add --append

travis encrypt MAPQUEST_OPEN_KEY="YZX" --add --append

travis encrypt OPENCAGE_API_KEY="YZX" --add --append
```

**Comment by dougnukem** [comment]
@codingsince1985 looks like I'd need to be a project administrator to setup travis/coveralls. 

If you're comfortable you can give me admin access to set it up and then revoke it once it's done.

**Comment by codingsince1985** [comment]
@dougnukem, I'm fine adding you as 2nd admin, did a quick search and it looks like there's no way to do it. Please let know if/how you've done it in Github.
I've signed in both travis and coveralls, and enabled the repo.
Anything else in .travis.yml needs to be done?

**Comment by dougnukem** [comment]
@codingsince1985 yeah sounds like you can't have another repo admin unless it's setup as an organization.
- https://github.com/account/organizations/new

The other thing we'd need is for you to run the cli travis commands and commit the changes to the `.travis.yml` file with geo API keys, and COVERALLS_TOKEN for the repo that you created on https://coveralls.io.

https://github.com/codingsince1985/geo-golang/pull/9#issuecomment-208896903


## Setting `.travis.yml` encrypted API keys

```
# Run from repo root and commit modified .travis.yml file
travis encrypt COVERALLS_TOKEN="XYZ" --add

travis encrypt GOOGLE_API_KEY="XYZ" --add --append

travis encrypt BING_API_KEY="YZX" --add --append

travis encrypt HERE_APP_ID="YZX" --add --append
travis encrypt HERE_APP_CODE="YZX" --add --append

travis encrypt MAPBOX_API_KEY="YZX" --add --append

travis encrypt MAPQUEST_NOMINATUM_KEY="YZX" --add --append

travis encrypt MAPQUEST_OPEN_KEY="YZX" --add --append

travis encrypt OPENCAGE_API_KEY="YZX" --add --append
```

**Comment by codingsince1985** [comment]
@dougnukem, apart from keys for Google and Mapbox, all other tokens are added.
I don't have Google's key (will check how to get one), and my Mapbox's key somehow doesn't work any more (will check why later. Yet another example why I'm not a big fan of mocking http responses).

**Comment by dougnukem** [comment]
@codingsince1985 let me dig into it, now that I have access to the repo I think I'll be able to put my test API keys in for the tests.

**Comment by dougnukem** [comment]
@codingsince1985 fixed build issues by adding my own encrypted keys for geo API stuff into the `.travis.yml`

**Pull request merged**
